steps:
  # Build the container image with caching
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/epistorm-gleam-api/gleam-seir-api:$COMMIT_SHA'
      - '--cache-from'
      - 'gcr.io/epistorm-gleam-api/gleam-seir-api:latest'  # Use the latest image for caching
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/epistorm-gleam-api/gleam-seir-api:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gleam-seir-api'
      - '--image'
      - 'gcr.io/epistorm-gleam-api/gleam-seir-api:$COMMIT_SHA'
      - '--region'
      - 'us-west1'

options:
  cache: true
images:
  - 'gcr.io/epistorm-gleam-api/gleam-seir-api:$COMMIT_SHA'
